### ISSUE TITLE
t/test_sqlite.t started to fail

### ISSUE THREAD

**Issue by eserte** [interchange/Dancer2-Plugin-Interchange6#4]
See subject. Sample fail report: http://www.cpantesters.org/cpan/report/95c46332-91d8-11ea-b1e4-96661f24ea8f

I suspect this happens with Dancer2 0.300003 but I have no statistical analysis available.

**Comment by SysPete** [comment]
Thanks @eserte, turned out to be a commit in Dancer2 0.300001. New release on its ways to CPAN very soon.
